server:
  servlet:
    context-path: /api/v1
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring:
  ## application name
  application:
    name: customer-service
  ## database config H2
  datasource:
    url: jdbc:h2:mem:custumerdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  ## H2 console config
  h2:
    console:
      enabled: true
      path: /h2-console
  ## jpa structure config
  jpa:
    show-sql: true
    format_sql: true

management: ##nos permite indicar que el endpoint a publicar es el health
  endpoints:
    web:
      exposure:
        include: health
