server:
  servlet:
    context-path: /api/v1
  port: 8085

spring:
  application:
    name: account-service


  datasource:
    url: jdbc:h2:mem:accountDB
    driverClassName: org.h2.Driver
    username: admin
    password: admin

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    format-sql: true #sirve para mostrar en los logs como formato sql


